sudo: false
language: csharp

notifications:
  email: false

branches:
  only:
    - master
    - develop
    - coverity_scan

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "C/kXFJlPYrePkPuF31IDYsIaPDqgUeiWWvSZZ94fwk2icPjMmAV8y6SMLIFXocoiAqqtBJJUg9jMRfoFOIAVNEwPqc9wddyT15iULkeU0Okh6dt1H9mFjoNHX90zf1gEF1RRWWO8v2zmBpAOGfRHHfK6NejTmrn4d+CGgLSkcvIBAtl5wMVoMoqrc4nXimI/mriul8IfFWjXd8eKmlyNyCG6/QFfapMvRVosraLZDuK0TgEwRPj/0qt8LwULkvETeOBca2bPyOreoDJDZj26BWVkOcV+RF3/rp5z1dCIPh77/ki2t7Dm0DO77PQgceYAQe26Jq3Gt91TQ4pp9ij7N7R95EG9xiduwoLXDjYRgN32O1Z8E+KlYvxXlR49JYgIVSpFS1XjZpYyvktyp4aLgCFkL85Y9B2jY3NLN0U8nFDafygqW0QxG0dO3QigEEyxYsKx/XW5Le+r1Ga2tNwJMpCqYqh5+zoip5xBxSqv7zRwvLSDzJ/2KEekVoqYfjQJcqsRoT7VFz7JrGAG5Q9+UVMIJgzjm/Q/AdsV/NpV8fTRtKHmkzNcfmq+3nmU4ZQmFQErrjppKgrMiitMNAkEM3S0vIO1ZUh09pfe/1uW54IWmhG+alzbeaJ+niaGBBRKwSZoibfnUECFJTAUftF/BRmprGwn6A8vbfWG5NUr2ik="

git:
  depth: 1

install:
  - nuget restore TS3AudioBot.sln
  - nuget install NUnit.Runners -OutputDirectory nunit

script:
  - xbuild /p:Configuration=Release TS3AudioBot.sln
  - mono ./nunit/NUnit.ConsoleRunner.*.*.*/tools/nunit3-console.exe ./TS3ABotUnitTests/bin/Release/TS3ABotUnitTests.dll

after_script:
  - chmod u+x ts3notify.sh
  - ./ts3notify.sh

addons:
  coverity_scan:
    project:
      name: "Splamy/TS3AudioBot"
      description: "TS3AudioBot uploaded from TravisCI"
    notification_email: splamyn@gmail.com
    build_command_prepend: "xbuild /t:Clean"
    build_command: "xbuild /t:Rebuild /p:Configuration=Release TS3AudioBot.sln"
    branch_pattern: coverity_scan